all:
	#python main.py --days 30 --currency BTC
	#python main.py  --currency BTC --onlywithdividend --onlywithask --days 30 --daysoffset 0 --nodownload
	python main.py  --currency BTC --onlywithdividend --onlywithask --days 30 --daysoffset 0

.PHONY: clean

clean:
	$(RM) data_in/*
	$(RM) data_out/*